import Head from "next/head";
import Image from "next/image";
import Slider from "@/components/Slider";
import Recommended from "@/components/Recommended";
import { useContext, useEffect, useState } from "react";
import { MyContext } from "../_app";
import SearchedContent from "@/components/SearchedContent";

export default function movies({ movies }: { movies: Movie[] }) {
  const context = useContext(MyContext);
  

  return (
    <>
      <Head>
        <title>Entertainment Web App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      {!context?.searchResult ? (
        <>
          <Slider
            trendingData={context.trendingData}
            setTrendingData={context.setTrendingData}
          />{" "}
          <Recommended
            recommendedData={context.recommendedData}
            setRecommendedData={context.setRecommendedData}
            wholeData={context.wholeData}
            setWholeData={context.setWholeData}
          />
        </>
      ) : (
        <SearchedContent wholeData={context.wholeData} setWholeData={context.setWholeData} />
      )}
    </>
  );
}
